apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu13-backend-deployment
  namespace: edu30
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edu13-backend
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/inject: "true"    
      labels:
        app: edu13-backend
    spec:
      containers:
      - name: edu13-backend
        image: shclub/edu13-backend
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
#        envFrom:
#        - configMapRef:
#            name: gw-configmap  
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
