apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- icis-apigw-deployment.yaml
- icis-apigw-svc.yaml
- icis-apigw-configmap.yaml
images:
- name: nexus.dspace.kt.co.kr/icis/icis-apigw
  newTag: develop-20220708074526
