apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: shclub/edu12-4
  newTag: "20230322024352"
- name: shclub/edu13-backend
  newTag: v12
